### ISSUE TITLE
Update Kubernetes configs - will fix a few things

### ISSUE THREAD

**Issue by incertum** [falcosecurity/deploy-kubernetes#95]
1. Missing `HOST_ROOT` env in initContainers `falco-driver-loader`

```yaml
env:
- name: HOST_ROOT
  value: /host
```

2.

For completeness suggest explicitly adding `HOST_ROOT` env to the falco container, plus add `FALCO_HOSTNAME` env as we now use it in Falco's `metrics` option and expose it as filter in `evt.hostname`, so it would be a great example template.

```yaml
env:
- name: FALCO_HOSTNAME
  valueFrom:
    fieldRef:
      fieldPath: spec.nodeName
- name: HOST_ROOT
  value: /host
```

3. DISREGARD

> I notice we mount the entire `/usr` which is not needed, suggest changing to the following in order to adopt best production practices (least access):

> ```yaml
> 
> volumes:
>  - name: usr-src-kernels-fs
>   hostPath:
>     path: /usr/src/kernels/
> ...
> 
> volumeMounts:
> - mountPath: /host/usr/src/kernels/
>   name: usr-src-kernels-fs
>   readOnly: true
> ...
> ```

4.

The docs here are not sufficient, happy to update them!
